name: Update Notebooks and refresh
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-notebooks:
    if: ( github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' )
    runs-on: ubuntu-latest
    steps:

      - name: See event name
        run: |
          echo "title ${title}"
          echo "actor ${actor}"
          echo "event_name ${event_name}"
        env:
          title: ${{ github.event.issue.title }}
          actor: ${{ github.actor }}
          event_name: ${{ github.event_name }}

      - name: Copy Repo Contents
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.9

      - name: install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get -y --force-yes install chromium-chromedriver
          npm install -g electron@6.1.4 orca
          pip3 install -r ./_notebooks/requirements.txt
          python3 -m ipykernel install --user --name python3
          sudo chmod -R 777 .

      - name : update notebooks
        id: update_nb
        run : |
          ./_action_files/run_notebooks.sh

      - name: convert notebooks and word docs to post
        uses: ./_action_files

      - name: setup directories for Jekyll build
        run: |
          rm -rf _site
          sudo chmod -R 777 .

      - name: Jekyll build
        uses: docker://hamelsmu/fastpages-jekyll
        with:
          args: bash -c "gem install bundler && keyll build -V"
        env:
          JEKYLL_ENV: 'production'

      - name: copy CNAME file into _site if CNAME exists
        run: |
          sudo chmod -R 777 _site/
          cp CNAME _site/ 2>/dev/null || :

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          publish_dir: ./_site
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true